### ISSUE TITLE
内存型mongo复制集搭建

### ISSUE THREAD

**Issue by knightFly** [knightFly/knightFly-blogs#2]
## 基于docker的内存型mongo复制集搭建
将MongoDB用作内存数据库（in-memory database），也即，根本就不让MongoDB把数据保存到磁盘中的这种用法，引起了越来越多的人的兴趣。这种用法对于以下应用场合来讲，超实用：
- 置于慢速RDBMS系统之前的写操作密集型高速缓存
- 嵌入式系统
- 无需持久化数据的PCI兼容系统
- 需要轻量级数据库而且库中数据可以很容易清除掉的单元测试（unit testing）

如果这一切可以实现就真是太优雅了：我们就能够巧妙地在不涉及磁盘操作的情况下利用MongoDB的查询/检索功能。可能你也知道，在99％的情况下，磁盘IO（特别是随机IO）是系统的瓶颈，而且，如果你要写入数据的话，磁盘操作是无法避免的。

MongoDB有一个非常酷的设计决策，就是她可以使用内存影射文件（memory-mapped file）来处理对磁盘文件中数据的读写请求。这也就是说，MongoDB并不对RAM和磁盘这两者进行区别对待，只是将文件看作一个巨大的数组，然后按照字节为单位访问其中的数据，剩下的都交由操作系统（OS）去处理！就是这个设计决策，才使得MongoDB可以无需任何修改就能够运行于RAM之中。

##### 编写 Dockerfile :
```
FROM localhub:5000/neusoft/mongo

ADD entrypoint.sh /entrypoint.sh
RUN chmod 777 /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
```
`entrypoint.sh`文件如下:
```shell
#!/bin/bash
set -e

mkdir -p /data/db

mount -t tmpfs -o size=${DATA_SIZE}M tmpfs /data/db/

if [ "${1:0:1}" = '-' ]; then
		set -- mongod "$@"
fi

# allow the container to be started with `--user`
if [ "$1" = 'mongod' -a "$(id -u)" = '0' ]; then
		chown -R mongodb /data/configdb /data/db
		exec gosu mongodb "$BASH_SOURCE" "$@"
fi

if [ "$1" = 'mongod' ]; then
		numa='numactl --interleave=all'
		if $numa true &> /dev/null; then
				set -- $numa "$@"
		fi
fi

exec "$@"
```
在`entrypoint.sh`中通过将`tmpfs`内存文件系统挂载到`/data/db`目录，然后启动`mongod`服务时将`/data/db`目录指定为数据库存储目录既可以实现内存型mongo。

##### 制作镜像
写完`Dockerfile`和`entrypoint.sh`文件后既可以制作镜像，如下:
```shell
sudo docker build -t localhub:5000/cloudtest/mongo-ram .
```
执行以上命令后会生成名为`localhub:5000/cloudtest/mongo-ram`的镜像，接着将该镜像 push 到本地仓库（本文档使用的本地仓库为： localhub:5000 ）
```shell
sudo docker push localhub:5000/cloudtest/mongo-ram
```

### 搭建mongo复制集
本实例搭建 3 个节点的mongo复制集。节点分别为 mongo1 , mongo2 , mongo3 。复制集名为 cloudtest。以下以 mongo1 为例。
##### 编写 K8S 的 RC 和 SVC 文件（mongo1为例）
1. mongo1-rc.yaml
```yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo1
  labels:
    name: mongo1
  namespace: cloudtest
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo1
    spec:
      containers:
      - name: mongo1
        image: localhub:5000/cloudtest/mongo-ram
        args:
        - /bin/bash
        - -c
        - mongod --dbpath /data/db --nojournal --smallfiles --noprealloc  --replSet cloudtest
        env:
        - name: DATA_SIZE
          value: "300"
        ports:
        - containerPort: 27017
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 10
          timeoutSeconds: 3
        securityContext:
          privileged: true
      restartPolicy: Always
```

2. mongo1-svc.yaml
```yaml
apiVersion: v1
kind: Service
metadata:
  name: mongo1
  labels:
    name: mongo1
  namespace: cloudtest
spec:
  selector:
    name: mongo1
  ports:
  - port: 27017
```
其他节点的RC 和 SVC 文件和 mongo1 节点的类似，只需要将相应的 `name` 和 `label` 改为对应的值。如 mongo2 节点可将其值改为 mongo2。

##### 启动 RC 和 SVC
```shell
kubectl create -f mongo1-rc.yaml
kubectl create -f mongo1-svc.yaml
```

##### 初始化 mongo 复制集
按照上面的步骤将所有节点的 mongo 服务全部启动起来后，使用如下命令来查看mongo服务的信息：
```shell
kubectl get svc | grep mongo
```
结果显示如下：
```
mongo1                    10.0.53.154    <none>        27017/TCP   71d
mongo2                    10.0.113.67    <none>        27017/TCP   71d
mongo3                    10.0.147.244   <none>        27017/TCP   71d
```
列出了我们启动成功后的 3 个mongo服务。我们使用 mongo1 服务的 集群ip `10.0.53.154`用来初始化mongo。

首先，我们编写一个复制集配置文件(config.js):
```js
var initconf={"_id":"cloudtest","members":
    [
      { "_id":0,"host":"mongo1.cloudtest:27017","priority":10 },
      { "_id":1,"host":"mongo2.cloudtest:27017","priority":9 },
      { "_id":2,"host":"mongo3.cloudtest:27017","priority":9 }
    ]
}
rs.initiate(initconf)
var status = rs.status()
print(JSON.stringify(status,null,"\t"))
```
`config.js`文件中 `host` 配置格式 ： 服务名.名称空间:端口号

接着使用如下命令初始化 复制集:
```shell
mongo --host 10.0.53.154:27017 config.js
```
其中 `--host` 赋予 `mongo1` 服务的 集群ip。命令执行成功会返回下面的数据:
```json
{
	"set": "cloudtest",
	"date": "2017-03-22T05:10:20.870Z",
	"myState": 1,
	"term": {
		"floatApprox": 95
	},
	"heartbeatIntervalMillis": {
		"floatApprox": 2000
	},
	"members": [
		{
			"_id": 0,
			"name": "mongo1.cloudtest:27017",
			"health": 1,
			"state": 1,
			"stateStr": "PRIMARY",
			"uptime": 1272032,
			"optime": {
				"ts": {
					"t": 1490086947,
					"i": 4
				},
				"t": {
					"floatApprox": 95
				}
			},
			"optimeDate": "2017-03-21T09:02:27.000Z",
			"electionTime": {
				"t": 1489812449,
				"i": 1
			},
			"electionDate": "2017-03-18T04:47:29.000Z",
			"configVersion": 1,
			"self": true
		},
		{
			"_id": 1,
			"name": "mongo2.cloudtest:27017",
			"health": 0,
			"state": 8,
			"stateStr": "SECONDARY",
			"uptime": 0,
			"optime": {
				"ts": {
					"t": 0,
					"i": 0
				},
				"t": {
					"floatApprox": -1,
					"top": -1,
					"bottom": -1
				}
			},
			"optimeDate": "1970-01-01T00:00:00.000Z",
			"lastHeartbeat": "2017-03-22T05:10:13.527Z",
			"lastHeartbeatRecv": "2017-03-08T07:45:32.965Z",
			"pingMs": {
				"floatApprox": 1
			},
			"lastHeartbeatMessage": "Couldn't get a connection within the time limit",
			"configVersion": -1
		},
		{
			"_id": 2,
			"name": "mongo3.cloudtest:27017",
			"health": 1,
			"state": 2,
			"stateStr": "SECONDARY",
			"uptime": 346981,
			"optime": {
				"ts": {
					"t": 1490086947,
					"i": 4
				},
				"t": {
					"floatApprox": 95
				}
			},
			"optimeDate": "2017-03-21T09:02:27.000Z",
			"lastHeartbeat": "2017-03-22T05:10:20.342Z",
			"lastHeartbeatRecv": "2017-03-22T05:10:20.347Z",
			"pingMs": {
				"floatApprox": 0
			},
			"syncingTo": "mongo1.cloudtest:27017",
			"configVersion": 1
		}
	],
	"ok": 1
}
```
从返回数据可知，mongo1 已经被选举为 主节点(PRIMARY) ， mongo2 和 mongo3 是从节点（SECONDARY）。

到此，3节点的内存型mongo复制集搭建完毕。
