### ISSUE TITLE
k8s集群api网关的设计与部署

### ISSUE THREAD

**Issue by knightFly** [knightFly/knightFly-blogs#3]
## API网关的设计与部署
k8s集群对外暴露服务主要有两种方式，hostPort 和 nodePort ， hostPort 是 POD 暴露端口的方式，其暴露的端口只能在 POD 所在的 node 上访问，而且端口很容易和node节点上的已用端口冲突；nodePort 是 service 暴露端口的方式，nodePort暴露的端口能在集群中的所有节点访问，但端口范围太小,当集群中需要暴露的服务太多时，会造成端口不够用。为了解决上述问题，我们设计了API网关统一暴露集群内的所有服务。

### api 网关设计思路
api网关使用 haproxy 和 confd 来实现。实现思路从以下3方面着手：
- 服务注册
> 当k8s创建服务时能够将服务的信息注册到 etcd 数据库中。

- 服务发现
> confd 能够监控 etcd 获取服务信息 ， 并更新 haproxy 的配置文件，加入新服务的路由。

- 服务路由
> haproxy 能够 重新加载更新后的配置文件，实现到集群服务的路由。

服务注册是k8s集群自动完成的，我们需要做的就是服务发现和服务路由。服务发现通过 confd 实现 ， 服务路由通过 haproxy 实现。

##### 安装 confd  
执行如下命令从源码安装confd：
```shell
$ mkdir -p $GOPATH/src/github.com/kelseyhightower
$ git clone https://github.com/kelseyhightower/confd.git $GOPATH/src/github.com/kelseyhightower/confd
$ cd $GOPATH/src/github.com/kelseyhightower/confd
$ ./build
```
执行完以上命令后，可以在 `bin/` 目录下生成 `confd` 可执行文件。

##### 制作 haproxy 和 confd 镜像

1. 配置 confd 的配置文件:<br>
先建立 api-gateway 目录，并将 confd 可执行文件拷贝到该目录。
```shell
$ mkdir api-gateway
$ cp $GOPATH/src/github.com/kelseyhightower/confd/bin/confd api-gateway/
```
进入 api-gateway 目录并创建 confd 的配置文件目录
```shell
$ mkdir -p cfg/confd/{conf.d,templates}
```
创建 `template resource` 文件：
```shell
$ touch /etc/confd/conf.d/haproxy.toml
```
编辑文件内容：
```
[template]
prefix = "/registry/services"
src = "haproxy.cfg.tmpl"
dest = "/etc/haproxy/haproxy.cfg"
keys = [
        "endpoints"
]
reload_cmd = "/haproxy-init stop || /haproxy-init start"
```
`prefix = "/registry/services"` 指向需要监控的 etcd 的key。 `src = "haproxy.cfg.tmpl"` 配置需要更新的模板文件， `dest = "/etc/haproxy/haproxy.cfg"` 配置需要更新的 haproxy 配置。`reload_cmd = "/haproxy-init stop || /haproxy-init start"` 设置当配置文件更新时需要执行的命令，此处执行 `haproxy-init` 来重启 `haproxy`服务。<br>
<br>
创建`source template`文件：
```shell
$ touch etc/confd/templates/haproxy.cfg.tmpl
```
编辑文件内容如下:
```
global
  daemon
  maxconn 256
defaults
  mode http
  option httpclose
  timeout connect 5000ms
  timeout client 50000ms
  timeout server 50000ms
resolvers mydns
  nameserver dns1 10.0.10.100:53
  resolve_retries       3
  timeout retry         1s
  hold valid           10s
frontend http-in
    bind *:8080
    acl url_healthz path_beg /healthz
    use_backend check_health if url_healthz
{{range $dir := lsdir "/endpoints"}} {{if eq $dir "itestcloud"}} {{$custdir := printf "/endpoints/%s/*" $dir}} {{range gets $custdir}} {{$js := json (.Value)}} {{$type := printf "%s" $js.metadata.labels.type}} {{if eq $type "api"}}
    acl url_{{$dir}}_{{base .Key}} path_beg  /api/{{$dir}}/{{base .Key}}
    use_backend {{base .Key}}_{{$dir}}_backend if url_{{$dir}}_{{base .Key}} {{end}} {{end}} {{end}} {{end}}
{{range $dir := lsdir "/endpoints"}} {{if eq $dir "itestcloud"}} {{$custdir := printf "/endpoints/%s/*" $dir}} {{range gets $custdir}} {{$js := json (.Value)}} {{$type := printf "%s" $js.metadata.labels.type}} {{if eq $type "api"}}
backend {{base .Key}}_{{$dir}}_backend
    reqrep ^([^\ :]*)\ /api/{{$dir}}/{{base .Key}}/(.*)     \1\ /\2 {{$data := base .Key}}
    server {{base .Key}} {{base .Key}}.{{$dir}}.svc.cluster.local:80  resolvers mydns {{end}} {{end}} {{end}}
{{end}}
```
该文件的里主要用了 go 的模板语言来编写，不懂的需要先了解 go 的模板语法和 confd 提供的模板函数。<br>
<br>

2. 编写 Dockerfile 文件：
进入`api-gateway`目录，新建 Dockerfile 文件：
```
$ cd api-gateway
$ touch Dockerfile
```
编辑Dockerfile：
```
FROM haproxy:1.6
RUN mkdir -p /etc/haproxy
ADD confd /usr/bin/
ADD cfg/confd /etc/confd
ADD haproxy-init /
RUN chmod a+x /haproxy-init
ADD run.sh /
RUN chmod 733 /run.sh
CMD ["/run.sh"]
```
该镜像基于 haproxy 基础镜像制作。`ADD confd /usr/bin/` 把 confd 可执行文件 拷贝到 `/usr/bin`目录下，`ADD etc/confd /etc/confd` 将 confd 的配置文件拷贝到容器的`/etc/confd`目录下。`ADD haproxy-init /`用于将 haproxy-init 脚本文件拷贝到容器更目录下， `ADD run.sh /` 将 `run.sh`启动文件拷到容器根目录。<br>
<br>
接下来创建并编辑`haproxy-init`文件：
```shell
#!/bin/sh
# This is our service name
BASENAME=haproxy
BIN=$BASENAME
CFG=/etc/$BASENAME/$BASENAME.cfg
[ -f $CFG ] || exit 1
start() {
  echo "Starting $BASENAME: "
  $BIN -f $CFG
}
stop() {
  pid=`ps -A|grep $BASENAME|awk '{print $1}'`
  echo "Shutting down $BASENAME: "
  kill -9 $pid
}
# See how we were called.
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  *)
    echo $"Usage: $BASENAME {start|stop}"
    exit 1
esac
exit $?
```
创建并编辑 `run.sh` 文件：
```shell
#! /bin/bash
/bin/bash -c "/haproxy-init start"
/usr/bin/confd
```

3.  制作镜像
```shell
$ cd api-gateway
$ sudo docker build -t localhub:5000/cloudtest/api-gateway .
$ sudo docker push localhub:5000/cloudtest/api-gateway
```

##### 部署 api-gateway 服务
编辑k8s的 RC 和 SVC 文件
1. haproxy-rc.yaml：
```yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: haproxy
  labels:
    name: haproxy
  namespace: cloudtest
spec:
  replicas: 1
  selector:
    name: haproxy
  template:
    metadata:
      labels:
        name: haproxy
    spec:
      containers:
      - name: haproxy
        image: localhub:5000/cloudtest/haproxy-confd:v3
        command:
        - /bin/bash
        - -c
        - /usr/bin/confd
         -confdir="/etc/confd"
         -backend="etcd"
         -scheme="http"
         -interval=5
         -node="http://10.4.60.200:8080/api/etcd"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      restartPolicy: Always
```

2. haproxy-svc.yaml
```yaml
apiVersion: v1
kind: Service
metadata:
  name: haproxy
  labels:
    name: haproxy
  namespace: cloudtest
spec:
  selector:
    name: haproxy
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 32000
```
启动api-gateway服务：
```shell
$ kubectl create -f haproxy-rc
$ kubectl create -f haproxy-svc
```
